apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistor
  labels:
    app: persistor
spec:
  selector:
    matchLabels:
      app: persistor
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: persistor
    spec:
      containers:
        - image: ghcr.io/cloud-lada/persistor:latest
          imagePullPolicy: IfNotPresent
          command:
            - /usr/bin/persistor
          args:
            - --event-reader-url=$(EVENT_READER_URL)
            - --database-url=$(DATABASE_URL)
            - --port=$(PORT)
          name: persistor
          envFrom:
            - configMapRef:
                name: persistor
            - secretRef:
                name: persistor
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 100Mi
