apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- envs:
  - env/config.env
  name: api

secretGenerator:
- envs:
  - env/secret.env
  name: api

generatorOptions:
  disableNameSuffixHash: true
