apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjob.yaml

secretGenerator:
  - name: dumper
    envs:
      - env/secret.env

configMapGenerator:
  - name: dumper
    envs:
      - env/config.env

generatorOptions:
  disableNameSuffixHash: true
