apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: ghcr.io/cloud-lada/dumper
  newTag: latest
- name: ghcr.io/cloud-lada/ingestor
  newTag: latest
- name: ghcr.io/cloud-lada/persistor
  newTag: latest

resources:
- ingestor
- persistor
- dumper
