apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: ghcr.io/cloud-lada/dumper
  newTag: v0.0.0
- name: ghcr.io/cloud-lada/ingestor
  newTag: v0.0.0
- name: ghcr.io/cloud-lada/persistor
  newTag: v0.0.0
- name: ghcr.io/cloud-lada/api
  newTag: v0.0.0

resources:
- ingestor
- persistor
- dumper
- api
