apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestor
  labels:
    app: ingestor
spec:
  selector:
    matchLabels:
      app: ingestor
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ingestor
    spec:
      containers:
        - image: ghcr.io/cloud-lada/ingestor:latest
          imagePullPolicy: IfNotPresent
          args:
            - --event-writer-url=$(EVENT_WRITER_URL)
            - --api-key=$(API_KEY)
            - --port=$(PORT)
          name: ingestor
          envFrom:
            - configMapRef:
                name: ingestor
            - secretRef:
                name: ingestor
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 100Mi
